/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef PHP_TEXCALLER_H
#define PHP_TEXCALLER_H

extern zend_module_entry texcaller_module_entry;
#define phpext_texcaller_ptr &texcaller_module_entry

#ifdef PHP_WIN32
# define PHP_TEXCALLER_API __declspec(dllexport)
#else
# define PHP_TEXCALLER_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(texcaller);
PHP_MSHUTDOWN_FUNCTION(texcaller);
PHP_RINIT_FUNCTION(texcaller);
PHP_RSHUTDOWN_FUNCTION(texcaller);
PHP_MINFO_FUNCTION(texcaller);

ZEND_NAMED_FUNCTION(_wrap_texcaller_convert);
ZEND_NAMED_FUNCTION(_wrap_texcaller_escape_latex);
#endif /* PHP_TEXCALLER_H */
