<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('texcaller')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_texcaller.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('texcaller.so')) return;
    } else {
      if (!dl('texcaller.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



abstract class texcaller {
	static function texcaller_convert($OUTPUT,$OUTPUT_,$source,$source_format,$result_format,$max_runs) {
		texcaller_convert($OUTPUT,$OUTPUT_,$source,$source_format,$result_format,$max_runs);
	}

	static function texcaller_escape_latex($s) {
		return texcaller_escape_latex($s);
	}
}

/* PHP Proxy Classes */

?>
